### ISSUE TITLE
!next command output changes

### ISSUE THREAD

**Issue by MacND** [MacND/voluspa#35]
!next currently lists the next 3 events, and it's pretty bulky.  There have also been requests to change the way the current info is displayed:

https://github.com/MacND/the-oracle-engine/issues/22 - See if you're in an event's fireteam without calling !fireteam
https://github.com/MacND/the-oracle-engine/issues/32 - Show UTC *and* local time in !next

I really want to slim this down, ideally using embeds but that in itself is an accessibility issue.  

Current example output:
---
Upcoming events:
**Last Wish Sherpa (lw-4)**
```
• Starting: February 15th @ 20:00 GMT
• Fireteam: 5/6  | !join lw-4
• Estimate: 6:00 | Power: 550
```
**Last Wish Sherpa (lw-5)**
```
• Starting: February 16th @ 18:00 GMT
• Fireteam: 6/6
• Estimate: 6:00 | Power: 550
```
**Scourge of the Past (scourge-5)**
```
• Starting: Not Set
• Fireteam: 6/6
• Estimate: 0:45 | Power: 640
```

**Comment by MacND** [comment]
Potential new codeblock output:
---
**• Last Wish Sherpa (lw-4)** - January 1st @ 21:00 GMT
    `Mac, Jethrain, AsherRose, Loop, and renegadeprincess (5/6)`
**• Scourge of the Past Sherpa (scourge-4)** - January 2nd @ 21:00 GMT
    **You**, `Mac, Jethrain, AsherRose, Loop, and renegadeprincess (6/6)`

![discord output](https://cdn.discordapp.com/attachments/351488554100195329/545300592541827082/unknown.png)

**Comment by alexismartin** [comment]
I think I'd prefer having my own name showing instead of You.

**Comment by MacND** [comment]
Took another run at it:
![discord output](https://cdn.discordapp.com/attachments/481867113040969729/545577789114286101/unknown.png)
